# Generated by Django 6.0.1 on 2026-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="importjob",
            name="review_rows",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="importjob",
            name="stage",
            field=models.CharField(
                choices=[
                    ("upload", "Upload"),
                    ("mapping", "Mapping"),
                    ("review", "Review"),
                    ("execution", "Execution"),
                ],
                default="upload",
                max_length=20,
            ),
        ),
    ]
