"""Shared offer-photo delete provenance contract."""

from __future__ import annotations

PHOTO_DELETE_ORIGIN_MANUAL = "manual"
PHOTO_DELETE_ORIGIN_OFFER_DELETED = "offer_deleted"
PHOTO_DELETE_ORIGIN_LISTING_DELETED = "listing_deleted"
PHOTO_DELETE_ORIGIN_OFFER_PURGED = "offer_purged"
PHOTO_DELETE_ORIGIN_LISTING_PURGED = "listing_purged"

PHOTO_DELETE_PARENT_SCOPE_OFFER = "offer"
PHOTO_DELETE_PARENT_SCOPE_LISTING = "listing"

PHOTO_DELETE_ORIGINS: tuple[str, ...] = (
    PHOTO_DELETE_ORIGIN_MANUAL,
    PHOTO_DELETE_ORIGIN_OFFER_DELETED,
    PHOTO_DELETE_ORIGIN_LISTING_DELETED,
    PHOTO_DELETE_ORIGIN_OFFER_PURGED,
    PHOTO_DELETE_ORIGIN_LISTING_PURGED,
)

PHOTO_DELETE_PARENT_SCOPES: tuple[str, ...] = (
    PHOTO_DELETE_PARENT_SCOPE_OFFER,
    PHOTO_DELETE_PARENT_SCOPE_LISTING,
)

__all__ = [
    "PHOTO_DELETE_ORIGIN_LISTING_DELETED",
    "PHOTO_DELETE_ORIGIN_LISTING_PURGED",
    "PHOTO_DELETE_ORIGIN_MANUAL",
    "PHOTO_DELETE_ORIGIN_OFFER_DELETED",
    "PHOTO_DELETE_ORIGIN_OFFER_PURGED",
    "PHOTO_DELETE_ORIGINS",
    "PHOTO_DELETE_PARENT_SCOPE_LISTING",
    "PHOTO_DELETE_PARENT_SCOPE_OFFER",
    "PHOTO_DELETE_PARENT_SCOPES",
]
