"""Explicit per-route policy registry (bank-grade no implicit defaults)."""

from __future__ import annotations

from core.contracts.http_policy import RouteBudget, RoutePolicy

ROUTE_POLICIES: dict[str, RoutePolicy] = {
    "audit/auth-events/": RoutePolicy(
        policy_id="route.audit_auth_events",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "audit/auth-events/count/": RoutePolicy(
        policy_id="route.audit_auth_events_count",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "audit/count/": RoutePolicy(
        policy_id="route.audit_count",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "audit/logs/": RoutePolicy(
        policy_id="route.audit_logs",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "audit/purge/": RoutePolicy(
        policy_id="route.audit_purge",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "audit/security-alerts/": RoutePolicy(
        policy_id="route.audit_security_alerts",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "audit/security-alerts/count/": RoutePolicy(
        policy_id="route.audit_security_alerts_count",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/all/": RoutePolicy(
        policy_id="route.cache_match_all",
        retry_class="CHEAP_READ",
        cost_class="EXPENSIVE",
        replay_mode="NONE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "cache/match/batch/": RoutePolicy(
        policy_id="route.cache_match_batch",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="BOUNDED",
        replay_mode="FULL_SAFE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "cache/match/clear/": RoutePolicy(
        policy_id="route.cache_match_clear",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/count/": RoutePolicy(
        policy_id="route.cache_match_count",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/counts/": RoutePolicy(
        policy_id="route.cache_match_counts",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="BOUNDED",
        replay_mode="FULL_SAFE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "cache/match/dirty/": RoutePolicy(
        policy_id="route.cache_match_dirty",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/get/": RoutePolicy(
        policy_id="route.cache_match_get",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/mark-all/": RoutePolicy(
        policy_id="route.cache_match_mark_all",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/mark-client/": RoutePolicy(
        policy_id="route.cache_match_mark_client",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/mark-wilaya/": RoutePolicy(
        policy_id="route.cache_match_mark_wilaya",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/missing/": RoutePolicy(
        policy_id="route.cache_match_missing",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "cache/match/rebuild/": RoutePolicy(
        policy_id="route.cache_match_rebuild",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "cache/match/rebuild/client/": RoutePolicy(
        policy_id="route.cache_match_rebuild_client",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "cache/match/rebuild/dirty/": RoutePolicy(
        policy_id="route.cache_match_rebuild_dirty",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "cache/match/rebuild/wilaya/": RoutePolicy(
        policy_id="route.cache_match_rebuild_wilaya",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "cache/match/status/": RoutePolicy(
        policy_id="route.cache_match_status",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "clients/": RoutePolicy(
        policy_id="route.clients",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=RouteBudget(p95_ms=350, max_payload_bytes=393216, max_scan_rows=1500),
        sla_facing=True,
    ),
    "clients/<int:client_id>/": RoutePolicy(
        policy_id="route.clients_int_client_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "clients/<int:client_id>/demandes/": RoutePolicy(
        policy_id="route.clients_int_client_id_demandes",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "clients/<int:client_id>/purge/": RoutePolicy(
        policy_id="route.clients_int_client_id_purge",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "clients/<int:client_id>/restore/": RoutePolicy(
        policy_id="route.clients_int_client_id_restore",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "clients/changes/": RoutePolicy(
        policy_id="route.clients_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "clients/count/": RoutePolicy(
        policy_id="route.clients_count",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "clients/deleted/": RoutePolicy(
        policy_id="route.clients_deleted",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "clients/phone-duplicates/": RoutePolicy(
        policy_id="route.clients_phone_duplicates",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/articles/<int:article_id>/": RoutePolicy(
        policy_id="route.crm_articles_int_article_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/articles/changes/": RoutePolicy(
        policy_id="route.crm_articles_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "crm/contracts/": RoutePolicy(
        policy_id="route.crm_contracts",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/activate/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id_activate",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/articles/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id_articles",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/articles/renumber/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id_articles_renumber",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/cancel/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id_cancel",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/clauses/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id_clauses",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/print/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id_print",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/purge/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id_purge",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/<int:contract_id>/restore/": RoutePolicy(
        policy_id="route.crm_contracts_int_contract_id_restore",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/contracts/changes/": RoutePolicy(
        policy_id="route.crm_contracts_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "crm/contracts/deleted/": RoutePolicy(
        policy_id="route.crm_contracts_deleted",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/visits/": RoutePolicy(
        policy_id="route.crm_visits",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/visits/<int:visit_id>/": RoutePolicy(
        policy_id="route.crm_visits_int_visit_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/visits/<int:visit_id>/purge/": RoutePolicy(
        policy_id="route.crm_visits_int_visit_id_purge",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/visits/<int:visit_id>/restore/": RoutePolicy(
        policy_id="route.crm_visits_int_visit_id_restore",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "crm/visits/changes/": RoutePolicy(
        policy_id="route.crm_visits_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "crm/visits/deleted/": RoutePolicy(
        policy_id="route.crm_visits_deleted",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "dashboard/": RoutePolicy(
        policy_id="route.dashboard",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=RouteBudget(p95_ms=350, max_payload_bytes=393216, max_scan_rows=1500),
        sla_facing=True,
    ),
    "demandes/<int:demande_id>/": RoutePolicy(
        policy_id="route.demandes_int_demande_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "demandes/<int:demande_id>/purge/": RoutePolicy(
        policy_id="route.demandes_int_demande_id_purge",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "demandes/<int:demande_id>/restore/": RoutePolicy(
        policy_id="route.demandes_int_demande_id_restore",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "demandes/changes/": RoutePolicy(
        policy_id="route.demandes_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "demandes/deleted/": RoutePolicy(
        policy_id="route.demandes_deleted",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "diagnostics/keys/enrollment-token/": RoutePolicy(
        policy_id="route.diagnostics_keys_enrollment_token",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "diagnostics/keys/register/": RoutePolicy(
        policy_id="route.diagnostics_keys_register",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "diagnostics/keys/revoke/": RoutePolicy(
        policy_id="route.diagnostics_keys_revoke",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "diagnostics/keys/rotate/": RoutePolicy(
        policy_id="route.diagnostics_keys_rotate",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "diagnostics/verify/": RoutePolicy(
        policy_id="route.diagnostics_verify",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "firewall-verification/": RoutePolicy(
        policy_id="route.firewall_verification",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "health/": RoutePolicy(
        policy_id="route.health",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "health/live/": RoutePolicy(
        policy_id="route.health_live",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "health/ready/": RoutePolicy(
        policy_id="route.health_ready",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "hub/front-door/identity/": RoutePolicy(
        policy_id="route.hub_front_door_identity",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "hub-manager/authorizations/": RoutePolicy(
        policy_id="route.hub_manager_authorizations",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=500, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "hub-manager/authorizations/consume/": RoutePolicy(
        policy_id="route.hub_manager_authorizations_consume",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=500, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "hub-manager/owner-state/": RoutePolicy(
        policy_id="route.hub_manager_owner_state",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "health/snapshot/": RoutePolicy(
        policy_id="route.health_snapshot",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "import/<str:session_id>/review/": RoutePolicy(
        policy_id="route.import_str_session_id_review",
        retry_class="CHEAP_READ",
        cost_class="EXPENSIVE",
        replay_mode="NONE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "import/<str:session_id>/review/submit/": RoutePolicy(
        policy_id="route.import_str_session_id_review_submit",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "import/admin/security-limits/": RoutePolicy(
        policy_id="route.import_admin_security_limits",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "import/admin/security-limits/reload/": RoutePolicy(
        policy_id="route.import_admin_security_limits_reload",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "import/complete/": RoutePolicy(
        policy_id="route.import_complete",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "import/execute/": RoutePolicy(
        policy_id="route.import_execute",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "import/<str:session_id>/cancel/": RoutePolicy(
        policy_id="route.import_str_session_id_cancel",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "import/presign/": RoutePolicy(
        policy_id="route.import_presign",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "import/preview/": RoutePolicy(
        policy_id="route.import_preview",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "import/status/<str:task_id>/": RoutePolicy(
        policy_id="route.import_status_str_task_id",
        retry_class="CHEAP_READ",
        cost_class="EXPENSIVE",
        replay_mode="NONE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "import/upload/": RoutePolicy(
        policy_id="route.import_upload",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "listings/": RoutePolicy(
        policy_id="route.listings",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=RouteBudget(p95_ms=350, max_payload_bytes=393216, max_scan_rows=1500),
        sla_facing=True,
    ),
    "listings/<int:listing_id>/": RoutePolicy(
        policy_id="route.listings_int_listing_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "listings/<int:listing_id>/offers/": RoutePolicy(
        policy_id="route.listings_int_listing_id_offers",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "listings/<int:listing_id>/purge/": RoutePolicy(
        policy_id="route.listings_int_listing_id_purge",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "listings/<int:listing_id>/restore/": RoutePolicy(
        policy_id="route.listings_int_listing_id_restore",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "listings/changes/": RoutePolicy(
        policy_id="route.listings_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "listings/count/": RoutePolicy(
        policy_id="route.listings_count",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "listings/deleted/": RoutePolicy(
        policy_id="route.listings_deleted",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "listings/phone-duplicates/": RoutePolicy(
        policy_id="route.listings_phone_duplicates",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "locations/": RoutePolicy(
        policy_id="route.locations",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "locations/changes/": RoutePolicy(
        policy_id="route.locations_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "lookup/actions/": RoutePolicy(
        policy_id="route.lookup_actions",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "lookup/actions/<int:action_id>/": RoutePolicy(
        policy_id="route.lookup_actions_int_action_id",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "lookup/property-types/": RoutePolicy(
        policy_id="route.lookup_property_types",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=RouteBudget(p95_ms=350, max_payload_bytes=393216, max_scan_rows=1500),
        sla_facing=True,
    ),
    "lookup/property-types/<int:type_id>/": RoutePolicy(
        policy_id="route.lookup_property_types_int_type_id",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "lookup/wilayas/": RoutePolicy(
        policy_id="route.lookup_wilayas",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=RouteBudget(p95_ms=350, max_payload_bytes=393216, max_scan_rows=1500),
        sla_facing=True,
    ),
    "lookup/wilayas/<int:wilaya_id>/": RoutePolicy(
        policy_id="route.lookup_wilayas_int_wilaya_id",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "matches/client/<int:client_id>/": RoutePolicy(
        policy_id="route.matches_client_int_client_id",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=RouteBudget(p95_ms=350, max_payload_bytes=393216, max_scan_rows=1500),
        sla_facing=True,
    ),
    "matches/clients/all/": RoutePolicy(
        policy_id="route.matches_clients_all",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "matches/clients/counts/": RoutePolicy(
        policy_id="route.matches_clients_counts",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="BOUNDED",
        replay_mode="FULL_SAFE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "matches/clients/wilaya/": RoutePolicy(
        policy_id="route.matches_clients_wilaya",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "matches/demandes/<int:demande_id>/": RoutePolicy(
        policy_id="route.matches_demandes_int_demande_id",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "matches/demandes/<int:demande_id>/expand/": RoutePolicy(
        policy_id="route.matches_demandes_int_demande_id_expand",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "matches/demandes/all/": RoutePolicy(
        policy_id="route.matches_demandes_all",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "matches/demandes/counts/": RoutePolicy(
        policy_id="route.matches_demandes_counts",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="BOUNDED",
        replay_mode="FULL_SAFE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "matches/listings/counts/": RoutePolicy(
        policy_id="route.matches_listings_counts",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="BOUNDED",
        replay_mode="FULL_SAFE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "matches/listings/all/": RoutePolicy(
        policy_id="route.matches_listings_all",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "matches/offers/counts/": RoutePolicy(
        policy_id="route.matches_offers_counts",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="BOUNDED",
        replay_mode="FULL_SAFE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "matches/offers/all/": RoutePolicy(
        policy_id="route.matches_offers_all",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="EXPENSIVE",
        replay_mode="FULL_SAFE",
        breaker_score=2,
        alert_budget=RouteBudget(p95_ms=5000, max_payload_bytes=2097152, max_scan_rows=20000),
        contract_budget=None,
    ),
    "meta/policy/": RoutePolicy(
        policy_id="route.meta_policy",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "meta/latency/": RoutePolicy(
        policy_id="route.meta_latency",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "notifications/": RoutePolicy(
        policy_id="route.notifications",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "notifications/clear/": RoutePolicy(
        policy_id="route.notifications_clear",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "notifications/mark-read/": RoutePolicy(
        policy_id="route.notifications_mark_read",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "notifications/mark-unread/": RoutePolicy(
        policy_id="route.notifications_mark_unread",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "notifications/purge/": RoutePolicy(
        policy_id="route.notifications_purge",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "notifications/unread-count/": RoutePolicy(
        policy_id="route.notifications_unread_count",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "offers/<int:offer_id>/": RoutePolicy(
        policy_id="route.offers_int_offer_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "offers/<int:offer_id>/photos/": RoutePolicy(
        policy_id="route.offers_int_offer_id_photos",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "offers/<int:offer_id>/purge/": RoutePolicy(
        policy_id="route.offers_int_offer_id_purge",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "offers/<int:offer_id>/restore/": RoutePolicy(
        policy_id="route.offers_int_offer_id_restore",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "offers/changes/": RoutePolicy(
        policy_id="route.offers_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "offers/deleted/": RoutePolicy(
        policy_id="route.offers_deleted",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "offers/photos/<int:photo_id>/": RoutePolicy(
        policy_id="route.offers_photos_int_photo_id",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "offers/photos/changes/": RoutePolicy(
        policy_id="route.offers_photos_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "secrets/status/": RoutePolicy(
        policy_id="route.secrets_status",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "settings/agency/": RoutePolicy(
        policy_id="route.settings_agency",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "settings/agency/changes/": RoutePolicy(
        policy_id="route.settings_agency_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "settings/agency/media/": RoutePolicy(
        policy_id="route.settings_agency_media",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "settings/agency/media/complete/": RoutePolicy(
        policy_id="route.settings_agency_media_complete",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "settings/agency/media/presign/": RoutePolicy(
        policy_id="route.settings_agency_media_presign",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "settings/agency/serial/": RoutePolicy(
        policy_id="route.settings_agency_serial",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "settings/agency/set/": RoutePolicy(
        policy_id="route.settings_agency_set",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "settings/user/": RoutePolicy(
        policy_id="route.settings_user",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "settings/user/set/": RoutePolicy(
        policy_id="route.settings_user_set",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "simulation/delete/": RoutePolicy(
        policy_id="route.simulation_delete",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "simulation/save/": RoutePolicy(
        policy_id="route.simulation_save",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "simulation/start/": RoutePolicy(
        policy_id="route.simulation_start",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "simulation/status/": RoutePolicy(
        policy_id="route.simulation_status",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "storage/complete-upload/": RoutePolicy(
        policy_id="route.storage_complete_upload",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "storage/delete/": RoutePolicy(
        policy_id="route.storage_delete",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "storage/presign-upload/": RoutePolicy(
        policy_id="route.storage_presign_upload",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "storage/presign/": RoutePolicy(
        policy_id="route.storage_presign",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "tasks/<str:task_id>/": RoutePolicy(
        policy_id="route.tasks_str_task_id",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "templates/": RoutePolicy(
        policy_id="route.templates",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "templates/<int:template_id>/": RoutePolicy(
        policy_id="route.templates_int_template_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "templates/changes/": RoutePolicy(
        policy_id="route.templates_changes",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "templates/reset-defaults/": RoutePolicy(
        policy_id="route.templates_reset_defaults",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/": RoutePolicy(
        policy_id="route.users",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/<int:user_id>/": RoutePolicy(
        policy_id="route.users_int_user_id",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/invites/": RoutePolicy(
        policy_id="route.users_invites",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/invites/<uuid:invite_id>/resend/": RoutePolicy(
        policy_id="route.users_invites_uuid_invite_id_resend",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/invites/<uuid:invite_id>/revoke/": RoutePolicy(
        policy_id="route.users_invites_uuid_invite_id_revoke",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/register/": RoutePolicy(
        policy_id="route.auth_register",
        retry_class="NO_RETRY",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=500, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/register/approve/<str:signed_token>/": RoutePolicy(
        policy_id="route.auth_register_approve",
        retry_class="NO_RETRY",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=500, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/register/blacklist/<str:signed_token>/": RoutePolicy(
        policy_id="route.auth_register_blacklist",
        retry_class="NO_RETRY",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=500, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/activate/": RoutePolicy(
        policy_id="route.auth_activate",
        retry_class="NO_RETRY",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=500, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/accept-invite/": RoutePolicy(
        policy_id="route.auth_accept_invite",
        retry_class="NO_RETRY",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=500, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/mfa/totp/": RoutePolicy(
        policy_id="route.auth_mfa_totp",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/mfa/totp/enroll/start/": RoutePolicy(
        policy_id="route.auth_mfa_totp_enroll_start",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/mfa/totp/enroll/confirm/": RoutePolicy(
        policy_id="route.auth_mfa_totp_enroll_confirm",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/mfa/totp/disable/": RoutePolicy(
        policy_id="route.auth_mfa_totp_disable",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/sessions/": RoutePolicy(
        policy_id="route.auth_sessions",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/sessions/<uuid:session_id>/revoke/": RoutePolicy(
        policy_id="route.auth_sessions_uuid_session_id_revoke",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "auth/sessions/revoke-all/": RoutePolicy(
        policy_id="route.auth_sessions_revoke_all",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "e2e/runtime/identity/": RoutePolicy(
        policy_id="route.e2e_runtime_identity",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "e2e/notifications/publish/": RoutePolicy(
        policy_id="route.e2e_notifications_publish",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "e2e/auth/revoke-other-sessions/": RoutePolicy(
        policy_id="route.e2e_auth_revoke_other_sessions",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "e2e/auth/revoke-session/": RoutePolicy(
        policy_id="route.e2e_auth_revoke_session",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "e2e/imports/pause-next/": RoutePolicy(
        policy_id="route.e2e_imports_pause_next",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "e2e/faults/inject/": RoutePolicy(
        policy_id="route.e2e_faults_inject",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "e2e/entities/inspect/": RoutePolicy(
        policy_id="route.e2e_entities_inspect",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/permissions/grants/": RoutePolicy(
        policy_id="route.users_permissions_grants",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="BOUNDED",
        replay_mode="FULL_SAFE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "users/permissions/grants/<int:request_id>/approve/": RoutePolicy(
        policy_id="route.users_permissions_grants_int_request_id_approve",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/permissions/grants/<int:request_id>/deny/": RoutePolicy(
        policy_id="route.users_permissions_grants_int_request_id_deny",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/permissions/grants/<int:request_id>/revoke/": RoutePolicy(
        policy_id="route.users_permissions_grants_int_request_id_revoke",
        retry_class="CAS_WRITE",
        cost_class="CHEAP",
        replay_mode="REFERENCE_ONLY",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "users/permissions/matrix/": RoutePolicy(
        policy_id="route.users_permissions_matrix",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=1048576, max_scan_rows=5000),
        contract_budget=None,
    ),
    "compliance/users/<int:user_id>/export/": RoutePolicy(
        policy_id="route.compliance_users_export",
        retry_class="CAS_WRITE",
        cost_class="BOUNDED",
        replay_mode="REFERENCE_ONLY",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "compliance/users/<int:user_id>/delete/": RoutePolicy(
        policy_id="route.compliance_users_delete",
        retry_class="CAS_WRITE",
        cost_class="BOUNDED",
        replay_mode="REFERENCE_ONLY",
        breaker_score=1,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "compliance/jobs/<uuid:job_id>/": RoutePolicy(
        policy_id="route.compliance_jobs_status",
        retry_class="CHEAP_READ",
        cost_class="CHEAP",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
    "compliance/exports/<uuid:job_id>/download/": RoutePolicy(
        policy_id="route.compliance_exports_download",
        retry_class="CHEAP_READ",
        cost_class="BOUNDED",
        replay_mode="NONE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=1000, max_payload_bytes=524288, max_scan_rows=1000),
        contract_budget=None,
    ),
    "visibility/<str:table>/<int:record_id>/": RoutePolicy(
        policy_id="route.visibility_str_table_int_record_id",
        retry_class="IDEMPOTENCY_KEY_WRITE",
        cost_class="CHEAP",
        replay_mode="FULL_SAFE",
        breaker_score=0,
        alert_budget=RouteBudget(p95_ms=250, max_payload_bytes=262144, max_scan_rows=1000),
        contract_budget=None,
    ),
}


def get_explicit_route_policy(route_path: str) -> RoutePolicy | None:
    return ROUTE_POLICIES.get(route_path)


__all__ = ["ROUTE_POLICIES", "get_explicit_route_policy", "RouteBudget", "RoutePolicy"]
