"""
Security and proxy-related settings.
"""

from __future__ import annotations

import os

from .settings_api import REST_FRAMEWORK
from .settings_base import DEBUG

TRUST_PROXY = os.environ.get("DJANGO_TRUST_PROXY", "0") == "1"
USE_X_FORWARDED_HOST = False
USE_X_FORWARDED_PORT = False
SECURE_PROXY_SSL_HEADER = None
SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_BROWSER_XSS_FILTER = False
SECURE_REFERRER_POLICY = None
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SECURE_FRAME_DENY = False
if TRUST_PROXY:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    DJANGO_NUM_PROXIES = int(os.environ.get("DJANGO_NUM_PROXIES", "1"))
    REST_FRAMEWORK["NUM_PROXIES"] = DJANGO_NUM_PROXIES
else:
    DJANGO_NUM_PROXIES = 0

if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_REFERRER_POLICY = os.environ.get(
        "SECURE_REFERRER_POLICY", "strict-origin-when-cross-origin"
    )

    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "1") == "1"
    SESSION_COOKIE_SECURE = os.environ.get("SESSION_COOKIE_SECURE", "1") == "1"
    CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", "1") == "1"

    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_FRAME_DENY = os.environ.get("SECURE_FRAME_DENY", "1") == "1"

__all__ = [
    "CSRF_COOKIE_SECURE",
    "DJANGO_NUM_PROXIES",
    "SECURE_BROWSER_XSS_FILTER",
    "SECURE_CONTENT_TYPE_NOSNIFF",
    "SECURE_FRAME_DENY",
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    "SECURE_HSTS_PRELOAD",
    "SECURE_HSTS_SECONDS",
    "SECURE_PROXY_SSL_HEADER",
    "SECURE_REFERRER_POLICY",
    "SECURE_SSL_REDIRECT",
    "SESSION_COOKIE_SECURE",
    "TRUST_PROXY",
    "USE_X_FORWARDED_HOST",
    "USE_X_FORWARDED_PORT",
]
