"""
Email and onboarding settings.
"""

from __future__ import annotations

import os

IMMOAPP_PLATFORM_ADMIN_EMAIL = os.environ.get("IMMOAPP_PLATFORM_ADMIN_EMAIL", "").strip()
IMMOAPP_PUBLIC_BASE_URL = os.environ.get("IMMOAPP_PUBLIC_BASE_URL", "").strip()

EMAIL_BACKEND = os.environ.get(
    "IMMOAPP_EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("IMMOAPP_EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("IMMOAPP_EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.environ.get("IMMOAPP_EMAIL_USE_TLS", "1").strip() == "1"
EMAIL_HOST_USER = os.environ.get("IMMOAPP_EMAIL_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("IMMOAPP_EMAIL_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("IMMOAPP_EMAIL_FROM", "ImmoApp <noreply@immoapp.io>")

IMMOAPP_ACTIVATION_CODE_EXPIRY_HOURS = int(
    os.environ.get("IMMOAPP_ACTIVATION_CODE_EXPIRY_HOURS", "72")
)
IMMOAPP_INVITE_CODE_EXPIRY_HOURS = int(os.environ.get("IMMOAPP_INVITE_CODE_EXPIRY_HOURS", "48"))
IMMOAPP_APPROVAL_TOKEN_EXPIRY_DAYS = int(os.environ.get("IMMOAPP_APPROVAL_TOKEN_EXPIRY_DAYS", "7"))
IMMOAPP_PENDING_REGISTRATION_EXPIRY_DAYS = int(
    os.environ.get("IMMOAPP_PENDING_REGISTRATION_EXPIRY_DAYS", "30")
)
IMMOAPP_INVITE_RESEND_COOLDOWN_SECONDS = int(
    os.environ.get("IMMOAPP_INVITE_RESEND_COOLDOWN_SECONDS", "3600")
)

__all__ = [
    "DEFAULT_FROM_EMAIL",
    "EMAIL_BACKEND",
    "EMAIL_HOST",
    "EMAIL_HOST_PASSWORD",
    "EMAIL_HOST_USER",
    "EMAIL_PORT",
    "EMAIL_USE_TLS",
    "IMMOAPP_ACTIVATION_CODE_EXPIRY_HOURS",
    "IMMOAPP_APPROVAL_TOKEN_EXPIRY_DAYS",
    "IMMOAPP_INVITE_CODE_EXPIRY_HOURS",
    "IMMOAPP_INVITE_RESEND_COOLDOWN_SECONDS",
    "IMMOAPP_PENDING_REGISTRATION_EXPIRY_DAYS",
    "IMMOAPP_PLATFORM_ADMIN_EMAIL",
    "IMMOAPP_PUBLIC_BASE_URL",
]
