# Generated by Django 6.0.1 on 2026-01-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agency",
            name="max_agents_per_manager",
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="agency",
            name="max_users",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
