# Generated by manual migration for import permissions

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_timezone_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_import",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="import_granted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The manager who granted import permission to this agent.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="import_grantees",
                to="accounts.user",
            ),
        ),
    ]
