# Generated by Django 6.0.2 on 2026-02-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_privilegeelevationrequest"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE accounts_user ALTER COLUMN mfa_totp_enabled SET DEFAULT FALSE; "
                "ALTER TABLE accounts_user ALTER COLUMN mfa_totp_secret SET DEFAULT ''; "
                "UPDATE accounts_user SET mfa_totp_enabled = FALSE WHERE mfa_totp_enabled IS NULL; "
                "UPDATE accounts_user SET mfa_totp_secret = '' WHERE mfa_totp_secret IS NULL;"
            ),
            reverse_sql=(
                "ALTER TABLE accounts_user ALTER COLUMN mfa_totp_enabled DROP DEFAULT; "
                "ALTER TABLE accounts_user ALTER COLUMN mfa_totp_secret DROP DEFAULT;"
            ),
        ),
    ]
