# Generated by Django 6.0.2 on 2026-02-27 04:07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_compliancejob"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="address_line1_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agency",
            name="address_line2_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agency",
            name="city_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agency",
            name="phone_number_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name_search_src",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_search_src",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_totp_secret_enc",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("agency_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(max_length=255)),
                ("registry_number", models.CharField(max_length=128)),
                ("agency_address", models.CharField(max_length=500)),
                ("agency_city", models.CharField(max_length=128)),
                ("agency_postal_code", models.CharField(max_length=32)),
                ("owner_first_name", models.CharField(max_length=100)),
                ("owner_last_name", models.CharField(max_length=100)),
                ("owner_phone", models.CharField(max_length=64)),
                ("agency_name_enc", models.TextField(blank=True, default="")),
                ("legal_name_enc", models.TextField(blank=True, default="")),
                ("registry_number_enc", models.TextField(blank=True, default="")),
                ("agency_address_enc", models.TextField(blank=True, default="")),
                ("agency_city_enc", models.TextField(blank=True, default="")),
                ("agency_postal_code_enc", models.TextField(blank=True, default="")),
                ("owner_first_name_enc", models.TextField(blank=True, default="")),
                ("owner_last_name_enc", models.TextField(blank=True, default="")),
                ("owner_phone_enc", models.TextField(blank=True, default="")),
                ("owner_email", models.EmailField(max_length=254, unique=True)),
                ("terms_accepted", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("blacklisted", "Blacklisted"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("approval_token_hash", models.CharField(blank=True, max_length=128)),
                ("activation_code_hash", models.CharField(blank=True, max_length=128)),
                ("activation_code_expires_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="acct_reg_status_idx"),
                    models.Index(fields=["expires_at"], name="acct_reg_exp_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("invite_name", models.CharField(max_length=200)),
                ("invite_name_enc", models.TextField(blank=True, default="")),
                ("invite_email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("manager", "Manager"),
                            ("agent", "Agent"),
                        ],
                        max_length=32,
                    ),
                ),
                ("invite_code_hash", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("last_sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resend_count", models.PositiveIntegerField(default=0)),
                (
                    "accepted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_invites",
                        to="accounts.agency",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_invites_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_invites_managed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["agency", "status", "expires_at"], name="acct_inv_status_idx"
                    ),
                    models.Index(fields=["invite_email", "status"], name="acct_inv_email_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("role", "agent"), ("manager__isnull", False)),
                            models.Q(("role", "manager"), ("manager__isnull", True)),
                            _connector="OR",
                        ),
                        name="acct_inv_role_manager_ck",
                    )
                ],
            },
        ),
    ]
