# Generated by Django 6.0.2 on 2026-03-05 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_user_and_invite_scale_indexes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
