"""Plain-language UI copy contract and guard constants."""

from __future__ import annotations

FORBIDDEN_UI_TERMS: tuple[str, ...] = (
    "mfa",
    "totp",
    "authentication",
    "session",
    "token",
    "otp",
    "privilege",
    "compliance",
    "rls",
    "tenant",
    "idempotency",
    "circuit breaker",
    "middleware",
    "serializer",
    "payload",
    "uuid",
    "endpoint",
    "api",
    "websocket",
    "schema",
    "migration",
    "query",
    "cache",
    "retry",
    "upstream",
    "downstream",
    "audit trail",
    "rbac",
    "acl",
    "oidc",
    "jwt",
    "sha",
    "ale",
    "encryption key",
    "sql",
    "orm",
    "celery",
    "worker",
    "beat",
    "queue",
    "broker",
)

REQUIRED_MENU_LABELS: tuple[str, ...] = (
    "Settings",
    "My Account",
    "Locations",
    "Contracts",
    "Activity History",
    "Connection Status",
    "Report a Problem",
    "Message Templates",
    "Team Members",
    "Agency Profile",
    "Manage Locations",
    "Recently Deleted",
)

REQUIRED_TAB_LABELS: tuple[str, ...] = (
    "Dashboard",
    "Matches",
    "Clients",
    "Properties",
    "Follow-up",
)

TECHNICAL_ID_PATTERNS: tuple[str, ...] = (
    "request id",
    "activation token",
    "session id",
    "record id",
    "job id",
)

CONTRACT_UI_FILES: tuple[str, ...] = (
    "app/main_window_menus.py",
    "app/main_window_tabs.py",
    "app/main_window_dialogs.py",
    "app/main_window_notifications.py",
    "app/main_window_status.py",
    "app/views/dashboard.py",
    "app/views/dashboard_ui.py",
    "app/views/dashboard_cards.py",
    "app/views/match_ui.py",
    "app/views/clients_v2_ui.py",
    "app/views/listings_v2_ui.py",
    "app/views/crm.py",
    "app/views/crm_visits.py",
    "app/views/crm_contracts.py",
    "app/views/dialogs/audit_logs_dialog.py",
    "app/views/dialogs/audit_logs_ui.py",
    "app/views/dialogs/health_dialog.py",
    "app/views/dialogs/trash_dialog.py",
    "app/views/dialogs/user_management_dialog.py",
    "app/views/dialogs/user_management_ui.py",
    "app/views/dialogs/contract_edit_dialog.py",
    "app/views/time_settings_dialog.py",
    "app/views/dialogs/agency_settings_dialog.py",
    "app/views/dialogs/agency_settings_ui.py",
    "app/views/dialogs/wa_templates_ui.py",
    "app/views/dialogs/notifications_dialog.py",
    "app/views/imports/wizard_dialog.py",
    "app/views/imports/step_upload.py",
    "app/views/imports/step_mapping.py",
    "app/views/imports/step_execution.py",
    "app/views/imports/step_summary.py",
    "app/widgets/offer_edit_dialog.py",
    "app/widgets/offer_form.py",
    "app/widgets/offer_form_labels.py",
    "app/widgets/offer_form_ui.py",
    "app/widgets/demande_edit_dialog_v2.py",
    "app/widgets/demande_form.py",
    "app/widgets/demande_form_labels.py",
    "app/widgets/demande_form_ui.py",
    "app/widgets/login_dialog.py",
    "app/widgets/login_dialog_ui.py",
    "app/widgets/register_dialog.py",
    "app/widgets/register_dialog_ui.py",
    "app/widgets/activate_dialog.py",
    "app/widgets/activate_dialog_ui.py",
    "app/widgets/join_team_dialog.py",
    "app/widgets/join_team_dialog_ui.py",
    "app/widgets/setup_wizard.py",
    "app/widgets/setup_wizard_ui.py",
    "app/widgets/quick_start_dialog.py",
    "app/widgets/quick_start_dialog_ui.py",
    "app/widgets/diagnostics_actions.py",
    "app/widgets/location_manager_dialog.py",
    "app/widgets/splash_startup.py",
)

NEW_UI_MODULES_WITH_ALL: tuple[str, ...] = (
    "app/services/ui_capabilities.py",
    "app/services/onboarding_analytics.py",
    "app/services/registration_repository.py",
    "app/services/server_discovery.py",
    "app/utils/time_humanize.py",
    "app/ui/ui_copy_contract.py",
    "app/widgets/register_dialog.py",
    "app/widgets/register_dialog_ui.py",
    "app/widgets/activate_dialog.py",
    "app/widgets/activate_dialog_ui.py",
    "app/widgets/join_team_dialog.py",
    "app/widgets/join_team_dialog_ui.py",
    "app/widgets/setup_wizard.py",
    "app/widgets/setup_wizard_ui.py",
    "app/widgets/quick_start_dialog.py",
    "app/widgets/quick_start_dialog_ui.py",
)

__all__ = [
    "CONTRACT_UI_FILES",
    "FORBIDDEN_UI_TERMS",
    "NEW_UI_MODULES_WITH_ALL",
    "REQUIRED_MENU_LABELS",
    "REQUIRED_TAB_LABELS",
    "TECHNICAL_ID_PATTERNS",
]
